package MiniProject;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class LetterPostShop extends javax.swing.JFrame {

    public LetterPostShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        btnCalculateShippingCost = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        rdoNormalLetter = new javax.swing.JRadioButton();
        rdoRegisterLetter = new javax.swing.JRadioButton();
        rdoEMSLetter = new javax.swing.JRadioButton();
        txtResult = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Letter Post Shop");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("ส่งจดหมาย");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ประเภทจดหมาย");

        jLabel3.setFont(new java.awt.Font("TH K2D July8", 1, 26)); // NOI18N
        jLabel3.setText("น้ำหนักจดหมาย (g)");

        txtWeight.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });

        btnCalculateShippingCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalculateShippingCost.setText("คำนวณราคา");
        btnCalculateShippingCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateShippingCostActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnGroup.add(rdoNormalLetter);
        rdoNormalLetter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdoNormalLetter.setText("ธรรมดา");

        btnGroup.add(rdoRegisterLetter);
        rdoRegisterLetter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdoRegisterLetter.setText("ลงทะเบียน");

        btnGroup.add(rdoEMSLetter);
        rdoEMSLetter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdoEMSLetter.setText("EMS");

        txtResult.setEditable(false);
        txtResult.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("ค่าบริการที่ต้องจ่าย");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("บาท");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCalculateShippingCost))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(rdoNormalLetter)
                        .addGap(18, 18, 18)
                        .addComponent(rdoRegisterLetter)
                        .addGap(14, 14, 14)
                        .addComponent(rdoEMSLetter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoNormalLetter)
                    .addComponent(rdoRegisterLetter)
                    .addComponent(rdoEMSLetter))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCalculateShippingCost)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateShippingCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateShippingCostActionPerformed
        String weights = txtWeight.getText();
        if (weights.length() > 0) {
            int normal = 0, register = 0, ems = 0;
            int weight = Integer.valueOf(weights);
            if (rdoNormalLetter.isSelected()) {
                closeRadioButton();
                normal = sendNormal(weight);
                if (normal != 0) {
                    txtResult.setText(Integer.toString(normal));
                } else {
                    enterNewInformation();
                }
            } else if (rdoRegisterLetter.isSelected()) {
                closeRadioButton();
                register = sendRegister(weight);
                if (register != 0) {
                    txtResult.setText(Integer.toString(register));
                } else {
                    enterNewInformation();
                }
            } else if (rdoEMSLetter.isSelected()) {
                closeRadioButton();
                ems = sendEms(weight);
                if (ems != 0) {
                    txtResult.setText(Integer.toString(ems));
                } else {
                    enterNewInformation();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "กรุณาเลือกประเภทของการส่งจดหมายครับ");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "กรุณากรอกน้ำหนักจดหมายด้วยครับ");
        }
    }//GEN-LAST:event_btnCalculateShippingCostActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        btnGroup.clearSelection();
        rdoNormalLetter.setEnabled(true);
        rdoRegisterLetter.setEnabled(true);
        rdoEMSLetter.setEnabled(true);
        txtWeight.setText("");
        txtWeight.setEditable(true);
        txtResult.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit ?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtWeightKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetterPostShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LetterPostShop().setVisible(true);
            }
        });
    }

    public static int sendNormal(int weight) {
        int normal = 0;
        if (weight < 20) {
            normal = 3;
        } else if (weight < 100) {
            normal = 5;
        } else if (weight < 250) {
            normal = 9;
        } else if (weight < 500) {
            normal = 15;
        } else if (weight < 1000) {
            normal = 25;
        } else if (weight < 2000) {
            normal = 45;
        }
        return normal;
    }

    public static int sendRegister(int weight) {
        if (weight < 2000) {
            return sendNormal(weight) + 13;
        } else {
            return 0;
        }
    }

    public static int sendEms(int weight) {
        int ems = 0;
        if (weight < 20) {
            ems = 27;
        } else if (weight < 100) {
            ems = 32;
        } else if (weight < 250) {
            ems = 37;
        } else if (weight < 500) {
            ems = 47;
        } else if (weight < 1000) {
            ems = 62;
        } else if (weight < 2000) {
            ems = 77;
        }
        return ems;
    }

    public void enterNewInformation() throws HeadlessException {
        JOptionPane.showMessageDialog(rootPane, "กรุณาป้อนน้ำหนักจดหมายใหม่ครับ");
        txtWeight.setText("");
        txtWeight.setEditable(true);
    }

    public void closeRadioButton() {
        rdoNormalLetter.setEnabled(false);
        rdoRegisterLetter.setEnabled(false);
        rdoEMSLetter.setEnabled(false);
        txtWeight.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateShippingCost;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rdoEMSLetter;
    private javax.swing.JRadioButton rdoNormalLetter;
    private javax.swing.JRadioButton rdoRegisterLetter;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
