package MiniProject;

import javax.swing.JOptionPane;

public class MoneyExchange extends javax.swing.JFrame {

    public MoneyExchange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnExchangeMoney = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBanknote1000 = new javax.swing.JTextField();
        txtBanknote500 = new javax.swing.JTextField();
        txtBanknote100 = new javax.swing.JTextField();
        txtBanknote50 = new javax.swing.JTextField();
        txtBanknote20 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCoin10 = new javax.swing.JTextField();
        txtCoin5 = new javax.swing.JTextField();
        txtCoin2 = new javax.swing.JTextField();
        txtCoin1 = new javax.swing.JTextField();
        Coin10 = new javax.swing.JLabel();
        Coin5 = new javax.swing.JLabel();
        Coin2 = new javax.swing.JLabel();
        Coin1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Money Exchange");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("แลกเงินเป็นธนบัตร/เหรียญ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("จำนวนเงิน");

        txtMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoneyKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("บาท");

        btnExchangeMoney.setBackground(new java.awt.Color(255, 255, 102));
        btnExchangeMoney.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnExchangeMoney.setText("แลกเงิน");
        btnExchangeMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExchangeMoneyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel4.setText("ธนบัตร 1000");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel5.setText("ธนบัตร 500");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel6.setText("ธนบัตร 100");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel7.setText("ธนบัตร 50");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel8.setText("ธนบัตร 20");

        txtBanknote1000.setEditable(false);
        txtBanknote1000.setBackground(new java.awt.Color(255, 204, 102));
        txtBanknote1000.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBanknote1000.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBanknote500.setEditable(false);
        txtBanknote500.setBackground(new java.awt.Color(255, 204, 102));
        txtBanknote500.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBanknote500.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBanknote100.setEditable(false);
        txtBanknote100.setBackground(new java.awt.Color(255, 204, 102));
        txtBanknote100.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBanknote100.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBanknote50.setEditable(false);
        txtBanknote50.setBackground(new java.awt.Color(255, 204, 102));
        txtBanknote50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBanknote50.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBanknote20.setEditable(false);
        txtBanknote20.setBackground(new java.awt.Color(255, 204, 102));
        txtBanknote20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBanknote20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel9.setText("ใบ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel10.setText("ใบ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel11.setText("ใบ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel12.setText("ใบ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel13.setText("ใบ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel14.setText("เหรียญ 10");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel15.setText("เหรียญ 5");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel16.setText("เหรียญ 2");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jLabel17.setText("เหรียญ 1");

        txtCoin10.setEditable(false);
        txtCoin10.setBackground(new java.awt.Color(204, 255, 255));
        txtCoin10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoin10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCoin5.setEditable(false);
        txtCoin5.setBackground(new java.awt.Color(204, 255, 255));
        txtCoin5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoin5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCoin2.setEditable(false);
        txtCoin2.setBackground(new java.awt.Color(204, 255, 255));
        txtCoin2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoin2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCoin1.setEditable(false);
        txtCoin1.setBackground(new java.awt.Color(204, 255, 255));
        txtCoin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCoin1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Coin10.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        Coin10.setText("เหรียญ");

        Coin5.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        Coin5.setText("เหรียญ");

        Coin2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        Coin2.setText("เหรียญ");

        Coin1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        Coin1.setText("เหรียญ");

        btnClear.setBackground(new java.awt.Color(204, 255, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 204, 204));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBanknote1000, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBanknote500, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBanknote100, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBanknote50, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBanknote20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCoin5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Coin5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Coin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Coin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCoin10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(Coin10))
                                    .addComponent(btnExchangeMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addGap(246, 246, 246)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMoney, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnExchangeMoney)
                        .addComponent(jLabel2)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBanknote1000, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBanknote500, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBanknote100, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBanknote20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBanknote50, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoin10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(Coin10))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoin5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(Coin5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(Coin2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(Coin1))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExchangeMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExchangeMoneyActionPerformed
        String bank1000 = "", bank500 = "", bank100 = "", bank50 = "", bank20 = "";
        String coin10 = "", coin5 = "", coin2 = "", coin1 = "";
        String moneys = txtMoney.getText();
        if (moneys.length() > 0) {
            int money = Integer.parseInt(moneys);
            if (money >= 1000) {
                bank1000 = "" + (money / 1000);
                money = money % 1000;
            }
            if (money >= 500) {
                bank500 = "" + (money / 500);
                money = money % 500;
            }
            if (money >= 100) {
                bank100 = "" + (money / 100);
                money = money % 100;
            }
            if (money >= 50) {
                bank50 = "" + (money / 50);
                money = money % 50;
            }
            if (money >= 20) {
                bank20 = "" + (money / 20);
                money = money % 20;
            }
            if (money >= 10) {
                coin10 = "" + (money / 10);
                money = money % 10;
            }
            if (money >= 5) {
                coin5 = "" + (money / 5);
                money = money % 5;
            }
            if (money >= 2) {
                coin2 = "" + (money / 2);
                money = money % 2;
            }
            if (money >= 1) {
                coin1 = "" + (money / 1);
            }
            txtBanknote1000.setText(bank1000);
            txtBanknote500.setText(bank500);
            txtBanknote100.setText(bank100);
            txtBanknote50.setText(bank50);
            txtBanknote20.setText(bank20);
            txtCoin10.setText(coin10);
            txtCoin5.setText(coin5);
            txtCoin2.setText(coin2);
            txtCoin1.setText(coin1);

        } else {
            JOptionPane.showMessageDialog(rootPane, "กรุณาระบุจำนวนเงินครับ");
        }
    }//GEN-LAST:event_btnExchangeMoneyActionPerformed

    private void txtMoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoneyKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMoneyKeyTyped

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtMoney.setText("");
        txtBanknote1000.setText("");
        txtBanknote500.setText("");
        txtBanknote100.setText("");
        txtBanknote50.setText("");
        txtBanknote20.setText("");
        txtCoin10.setText("");
        txtCoin5.setText("");
        txtCoin2.setText("");
        txtCoin1.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit ?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyExchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyExchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Coin1;
    private javax.swing.JLabel Coin10;
    private javax.swing.JLabel Coin2;
    private javax.swing.JLabel Coin5;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExchangeMoney;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBanknote100;
    private javax.swing.JTextField txtBanknote1000;
    private javax.swing.JTextField txtBanknote20;
    private javax.swing.JTextField txtBanknote50;
    private javax.swing.JTextField txtBanknote500;
    private javax.swing.JTextField txtCoin1;
    private javax.swing.JTextField txtCoin10;
    private javax.swing.JTextField txtCoin2;
    private javax.swing.JTextField txtCoin5;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables
}
